### ISSUE TITLE
Add option to disable C# 10 features (e.g. global usings)

### ISSUE THREAD

**Issue by mikoro** [bottlenoselabs/c2cs#146]
When trying to use the generated C# file in Unity I get the following errors:

```
Plugin.gen.cs(14,1): error CS8773: Feature 'global using directive' is not available in C# 9.0. Please use language version 10.0 or greater.
Plugin.gen.cs(22,1): error CS8773: Feature 'file-scoped namespace' is not available in C# 9.0. Please use language version 10.0 or greater.
```

It would be nice to be able to turn off these features during the code generation.

**Comment by lithiumtoast** [comment]
Thanks, I removed `global using` for just `using` and added support for optional file scoped namespace in #147

**Comment by lithiumtoast** [comment]
Part of v6.10
