### ISSUE TITLE
`va_list`

### ISSUE THREAD

**Issue by lithiumtoast** [bottlenoselabs/c2cs#15]
Found when generating bindings for flecs: https://github.com/SanderMertens/flecs

```c
/* Append format string with argument list to a buffer.
 * Returns false when max is reached, true when there is still space */
FLECS_API
bool ecs_strbuf_vappend(
    ecs_strbuf_t *buffer,
    const char *fmt,
    va_list args);
```

It's not clear how `va_list` should be handled.

There is some discussion here on a similar issue: https://github.com/dotnet/runtime/issues/9316

**Comment by lithiumtoast** [comment]
There is no immediate clear way to proceed with this. Best to tread water on this and look into it again at a future date.

For now, `va_list` is remapped into `IntPtr` where necessary to avoid compilation errors.

**Comment by mfkl** [comment]
heya, this might interest you https://github.com/jeremyVignelles/va-list-interop-demo

**Comment by lithiumtoast** [comment]
@mfkl Thanks.

> va_list reading seems hard to do in a cross-platform way. Each platforms has its own implementation and I'm not sure it would work.

Rough. I'm working on adding support for multi-pass so that Clang can parse the translation unit using cross-compilation. Once that is finished I can expand the integration tests to do a dry-run of calling C# bindgen code for each platform and see what passes / fails.

**Comment by lithiumtoast** [comment]
Now that multi-pass is in, I'm taking a look at this again. While it would be interesting to do, I don't think I'm very interested in adding support right now myself. If someone wants to take a crack at it, I'm always open to contributions.

**Comment by lithiumtoast** [comment]
With usage of `DisableRuntimeMarshallingAttribute` .NET variadic argument method signatures are not supported; closing this out because `DisableRuntimeMarshallingAttribute` is what should be used for .NET 7+.
