### ISSUE TITLE
Sanitize unnamed const params

### ISSUE THREAD

**Issue by waldnercharles** [bottlenoselabs/c2cs#72]
It seems like unnamed const pointers aren't being sanitized correctly for function pointers.

The issue is with the 2nd parameter: `HRESULT (IRpcStubBuffer *, IID *const, void **)`

`IID` and `IID*` exist in the types dictionary, but, `TypeNameMapFunctionPointer` is looking for `IID*const`.

Possible test cases:
```
const int *ptr;
const int* ptr;
int const *ptr;
int const* ptr;
const int const *ptr;
const int const* ptr;
```

**Comment by lithiumtoast** [comment]
Hm, okay I'll add it to the integration tests after the `multi-pass` branch is merged.

**Comment by lithiumtoast** [comment]
Merged the branch in. I'll take a look at this tomorrow.

**Comment by lithiumtoast** [comment]
Added tests for this using a function declaration, but I can't seem to reproduce it. I suspect it got fixed when I merged in multipass branch. If you have the problem happen to you again let me know.
