### ISSUE TITLE
Fields in anonymous union inside a struct is not properly handled as documented.

### ISSUE THREAD

**Issue by AlseinX** [bottlenoselabs/c2cs#75]
C definition inside the header file:

```
struct SomeStruct
{
   // other fields
    union
    {
        struct Foo foo;
        struct Bar bar;
    };
    //other fields
};
```

The struct is correctly taken as `LayoutKind.Explicit`, and the field offsets of the normal fields are correctly calculated, but the fields inside the anonymous union is simply ignored.

**Comment by lithiumtoast** [comment]
Thanks @AlseinX 👍 

I'll add it to the integration tests once multipass is finished (working on it).

**Comment by AlseinX** [comment]
> Thanks @AlseinX 👍
> 
> I'll add it to the integration tests once multipass is finished (working on it).

Would a quick-fix be released to solve this problem?

**Comment by lithiumtoast** [comment]
I merged the branch in. I'll take a look at this tomorrow.

**Comment by lithiumtoast** [comment]
Found the issue, working on a solution now.
